# Generated by Django 5.2.9 on 2026-01-04 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=100, verbose_name='Sobrenome')),
                ('remuneracao', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Remuneração')),
                ('tempo_de_servico', models.IntegerField(verbose_name='Tempo de Serviço (anos)')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
            ],
        ),
    ]
